FROM node

RUN mkdir -p /app

WORKDIR /app

COPY frontend/package.json /app/package.json

RUN npm install

COPY frontend/ /app

RUN npm run build

ENV NUXT_HOST=0.0.0.0

ENV PROXY_API=$PROXY_API

CMD [ "npm", "start" ]
