version: '3'
services:
  database:
    container_name: database
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: $POSTGRES_ADMIN_NAME
      POSTGRES_PASSWORD: $POSTGRES_ADMIN_PW
      POSTGRES_DB: "wareneingang"
    volumes:
      - ./docker/postgres:/var/lib/postgresql/data
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile-Backend
    ports:
      - "8080:8080"
    environment:
      TESTING_MAIL_ADDRESS: $TESTING_MAIL_ADDRESS
      MAIL_USERNAME: $MAIL_USERNAME
      MAIL_PW: $MAIL_PW
      SPRING_DATASOURCE_URL: jdbc:postgresql://database/wareneingang
      SPRING_DATASOURCE_USERNAME: $POSTGRES_ADMIN_NAME
      SPRING_DATASOURCE_PASSWORD: $POSTGRES_ADMIN_PW
    depends_on:
      - database
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile-Frontend
    environment:
      PROXY_API: http://java:8080/
    ports:
      - 3000:3000